version: '3'

env_file:
  - .env.prod

services:
  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${RDS_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${RDS_DB_NAME}
      - MYSQL_USER=${RDS_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${RDS_DATABASE_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fastapi:
    image: kyeong6/eatceed:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - mariadb
      - redis
      - elasticsearch

  data-loader:
    image: kyeong6/data-loader:latest
    volumes:
      - ./data:/app/data
    env_file:
      - .env.prod
    depends_on:
      - elasticsearch
