version: '3'
services:
  mariadb:
    image: mariadb:10.6
    container_name: local-mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=eatceed
      - MYSQL_DATABASE=gaebaljip
      - MYSQL_USER=gaebaljip-local
      - MYSQL_PASSWORD=gaebaljip-local
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: local-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
      - ELASTIC_USERNAME=gaebaljip-local
      - ELASTIC_PASSWORD=gaebaljip-local
    ports:
      - "9200:9200"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    # 데이터 적재시 연결 보장하기 위한 healthcheck
    # data-loader가 depneds_on을 사용하고 있지만, ES 컨테이너가 시작되는 것만 확인하지 서비스 완전히 준비된 것을 보장하지 않음
    # 결국 ES 컨테이너가 "green" 상태가 될 때까지 대기하도록 설정 진행
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  redis:
    image: redis:6.2
    container_name: local-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=gaebaljip-local
    command: ["redis-server", "--requirepass", "gaebaljip-local"]
    volumes:
      - ./redis_data:/data


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: local-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://local-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=gaebaljip-local
      - ELASTICSEARCH_PASSWORD=gaebaljip-local
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


  # fastapi_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   depends_on:
  #     - mariadb
  #     - elasticsearch
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ELASTICSEARCH_HOST=local-elasticsearch:9200
  #     - MARIADB_HOST=local-mariadb
  #     - MARIADB_USER=gaebaljip-local
  #     - MARIADB_PASSWORD=gaebaljip-local
  #     - MARIADB_DB=gaebaljip

  data_loader:
    build:
      context: .
      dockerfile: Dockerfile.data
    volumes:
      - ./data:/app/data
    # 개발환경 : .env.dev
    env_file:
      - .env.dev
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - APP_ENV=dev
    restart: on-failure