version: '3'
services:
  mariadb:
    image: mariadb:10.6
    container_name: local-mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=eatceed
      - MYSQL_DATABASE=gaebaljip
      - MYSQL_USER=gaebaljip-local
      - MYSQL_PASSWORD=gaebaljip-local
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql 

  redis:
    image: redis:6.2
    container_name: local-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=gaebaljip-local
    command: ["redis-server", "--requirepass", "gaebaljip-local"]
    volumes:
      - ./redis_data:/data


  # fastapi_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   depends_on:
  #     - mariadb
  #     - elasticsearch
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ELASTICSEARCH_HOST=local-elasticsearch:9200
  #     - MARIADB_HOST=local-mariadb
  #     - MARIADB_USER=gaebaljip-local
  #     - MARIADB_PASSWORD=gaebaljip-local
  #     - MARIADB_DB=gaebaljip

  data_loader:
    build:
      context: .
      dockerfile: Dockerfile.data
    volumes:
      - ./data:/app/data
    # 개발환경 : .env.dev
    env_file:
      - .env.dev
    environment:
      - APP_ENV=dev
    restart: on-failure